### ISSUE TITLE
Hacktoberfest 2017

### ISSUE THREAD

**Issue by Maikuolan** [CIDRAM/Aggregator#1]
Hacktoberfest by Digital Ocean will be running again this year through the month of October 2017. If anyone sees any room for improvement to the codebase, has ideas, suggestions, bug-fixes, or whatever else, if you want to win a free Hacktoberfest t-shirt and some stickers, consider signing up for this year and sending some pull requests to this repository. :-)

For more details: __https://hacktoberfest.digitalocean.com/#details__

*Issue will remain open until the end of October.*

**Comment by Logan1x** [comment]
does today's contribution will counted in the fest? PR for issues with 'Hacktoberfest ' label.

**Comment by Lubits** [comment]
According to Digital Ocean's website:
> To get a shirt, you must make four pull requests between October 1–31 in any timezone.

I don't think a PR in September will count.

**Comment by Logan1x** [comment]
OK Thanks @HanQuang

**Comment by Maikuolan** [comment]
Correct: In order to be counted, PRs must be sent from October 1 to October 31. I look forward to seeing them. :-)

**Comment by ansh-ptel** [comment]
4 PR was done. where to fill details?

**Comment by DanielRuf** [comment]
@ansh-ptel https://hacktoberfest.digitalocean.com/sign_up/register
