### ISSUE TITLE
Feature: passing an array to $input

### ISSUE THREAD

**Issue by nistorj** [CIDRAM/Aggregator#9]
Hi again, very handy stuff you have, thanks!

I'm wondering if it would be possible to have the $input figure out if it's a simple pass of plain data or an array.  To give you some context we have a program that writes out a flat file with a series of prefixes of varying lengths, both v4/v6.  Right now when we pass the data we do it this way:

```
 if (($addresses = file($routefile)) == FALSE)
  {
    status(STATUS_WARNING, "Unable to open route file (might be empty), skipping.");
    return FALSE;
  }

  // First normalize the routes, no array.
  $addresses_normal = implode("", $addresses);

  // Process the aggregation
  $addresses_agg = aggregate($addresses_normal);

  // Return them in an array
  return explode(" ", $addresses_agg);
```

I'm wondering if it's possible to add the ability to detect if an array is being passed and do the magic within the Input?

**Comment by Maikuolan** [comment]
> I'm wondering if it's possible to add the ability to detect if an array is being passed and do the magic within the Input?

Sounds like a good idea; I reckon we could do that. :-)

**Comment by Maikuolan** [comment]
Done. :-)

**Comment by nistorj** [comment]
many thanks!
